# Generated by Django 4.2.7 on 2023-11-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_at'},
        ),
    ]
